// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LaPurisima.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LaPurisima.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MailLabel {
            get {
                return ResourceManager.GetString("MailLabel", resourceCulture);
            }
        }
        
        internal static string PassLabel {
            get {
                return ResourceManager.GetString("PassLabel", resourceCulture);
            }
        }
        
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        internal static string ForgotPassButtonText {
            get {
                return ResourceManager.GetString("ForgotPassButtonText", resourceCulture);
            }
        }
        
        internal static string NewUserText {
            get {
                return ResourceManager.GetString("NewUserText", resourceCulture);
            }
        }
        
        internal static string WriteMailLabel {
            get {
                return ResourceManager.GetString("WriteMailLabel", resourceCulture);
            }
        }
        
        internal static string RecuperarButtonText {
            get {
                return ResourceManager.GetString("RecuperarButtonText", resourceCulture);
            }
        }
        
        internal static string IngresaText {
            get {
                return ResourceManager.GetString("IngresaText", resourceCulture);
            }
        }
        
        internal static string CodeLabelText {
            get {
                return ResourceManager.GetString("CodeLabelText", resourceCulture);
            }
        }
        
        internal static string VerifyCodeText {
            get {
                return ResourceManager.GetString("VerifyCodeText", resourceCulture);
            }
        }
        
        internal static string CambiarText {
            get {
                return ResourceManager.GetString("CambiarText", resourceCulture);
            }
        }
        
        internal static string NuevoPassText {
            get {
                return ResourceManager.GetString("NuevoPassText", resourceCulture);
            }
        }
        
        internal static string NuevoPassConfText {
            get {
                return ResourceManager.GetString("NuevoPassConfText", resourceCulture);
            }
        }
        
        internal static string MensajeAltaText {
            get {
                return ResourceManager.GetString("MensajeAltaText", resourceCulture);
            }
        }
        
        internal static string NameAltaText {
            get {
                return ResourceManager.GetString("NameAltaText", resourceCulture);
            }
        }
        
        internal static string MailAltaText {
            get {
                return ResourceManager.GetString("MailAltaText", resourceCulture);
            }
        }
        
        internal static string PassAltaText {
            get {
                return ResourceManager.GetString("PassAltaText", resourceCulture);
            }
        }
        
        internal static string PassConAltaText {
            get {
                return ResourceManager.GetString("PassConAltaText", resourceCulture);
            }
        }
        
        internal static string CalleAltaText {
            get {
                return ResourceManager.GetString("CalleAltaText", resourceCulture);
            }
        }
        
        internal static string ColoniaAltaText {
            get {
                return ResourceManager.GetString("ColoniaAltaText", resourceCulture);
            }
        }
        
        internal static string CPAltaText {
            get {
                return ResourceManager.GetString("CPAltaText", resourceCulture);
            }
        }
        
        internal static string BetweenAltaText {
            get {
                return ResourceManager.GetString("BetweenAltaText", resourceCulture);
            }
        }
        
        internal static string UploadImageButtonText {
            get {
                return ResourceManager.GetString("UploadImageButtonText", resourceCulture);
            }
        }
        
        internal static string RegistrarButtonText {
            get {
                return ResourceManager.GetString("RegistrarButtonText", resourceCulture);
            }
        }
        
        internal static string NombreProfileText {
            get {
                return ResourceManager.GetString("NombreProfileText", resourceCulture);
            }
        }
        
        internal static string GuardarProfileText {
            get {
                return ResourceManager.GetString("GuardarProfileText", resourceCulture);
            }
        }
        
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        internal static string ErrorMessageEmail {
            get {
                return ResourceManager.GetString("ErrorMessageEmail", resourceCulture);
            }
        }
        
        internal static string ErrorMessageDoesntExist {
            get {
                return ResourceManager.GetString("ErrorMessageDoesntExist", resourceCulture);
            }
        }
    }
}
